"""Local dashboard; all employer content is inserted as text, never HTML."""
BOARD_HTML = r'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Job board</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#f5f7fb;color:#223049;font:14px/1.6 system-ui}main{max-width:1200px;margin:auto;padding:40px 24px}h1{font-size:32px;margin:0}h2{font-size:19px;margin:4px 0}.muted{color:#65738b}.toolbar,.meta,.actions{display:flex;gap:12px;flex-wrap:wrap;align-items:center}.toolbar{margin:22px 0}.toolbar input{flex:1;min-width:210px}input,select,textarea,button{font:inherit;padding:9px 12px;border:1px solid #ced7e5;border-radius:8px;background:white;color:inherit}button,a.primary{background:#254576;color:white;cursor:pointer;border:0;border-radius:8px;padding:9px 14px;text-decoration:none}a{color:#254576}textarea{width:100%;min-height:80px;resize:vertical}.card{background:white;border:1px solid #e0e6ee;border-radius:14px;padding:22px;margin:14px 0;box-shadow:0 5px 20px #19345005}.badge{background:#eaf0fa;border-radius:6px;padding:3px 8px;font-size:12px}.details{white-space:pre-wrap;overflow-wrap:anywhere}summary{cursor:pointer;color:#254576;margin:12px 0}.notes{margin:12px 0 8px}#notice{padding:12px 16px;background:#eaf0fa;border-radius:9px}#count{margin:12px 0}.error{color:#a23232}.saved{color:#21724d}button:disabled{opacity:.5}label{display:inline-flex;gap:6px;align-items:center}.field{border-left:3px solid #dde5f0;padding-left:12px;margin:14px 0}#more{margin:12px 0}@media(max-width:600px){main{padding:22px 14px}.card{padding:16px}.toolbar>*{width:100%}.toolbar label{width:auto}h1{font-size:27px}}
input[type=checkbox]{width:16px;min-width:16px;flex:0;padding:0}.toolbar label input[type=checkbox]{min-width:16px;flex:0}
</style><main><p class="muted">PRIVATE JOB SEARCH WORKSPACE</p><h1>Your job board</h1><p class="muted">Find the right roles. Apply yourself. Keep everything tracked.</p><p id="notice">Default ranking: 70% Jev relevance + 30% recency (7-day decay). Unassessed jobs use only the recency component. No automatic applications.</p>
<div class="toolbar"><input id="search" type="search" placeholder="Search company, role, location, or notes" aria-label="Search jobs"><select id="status" aria-label="Filter status"><option value="all">All statuses</option></select><select id="portal" aria-label="Filter source"><option value="all">All sources</option><option>ashby</option><option>greenhouse</option><option>lever</option></select><select id="sort" aria-label="Sort jobs"><option value="balanced">Relevant + recent</option><option value="newest">Newest first</option><option value="fit">Best fit</option></select><label><input id="unverified" type="checkbox">Older / unverified</label><label><input id="closed" type="checkbox">Closed</label><button id="refresh">Refresh</button><a href="/api/export">Export tracking CSV</a></div><p id="count" aria-live="polite"></p><div id="jobs"></div><button id="more" hidden>Show more</button></main>
<script>
const statuses=['new','saved','applied','interviewing','offer','rejected','skipped','needs_verification'];const label=s=>s.replaceAll('_',' ').replace(/^./,c=>c.toUpperCase());let jobs=[],limit=60;
const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e};const $=id=>document.getElementById(id);
statuses.forEach(s=>{const o=el('option',label(s));o.value=s;$('status').append(o)});
const date=s=>s?new Date(s).toLocaleDateString():'';
function selected(){const query=$('search').value.toLowerCase().trim();return jobs.filter(j=>($('status').value==='all'||j.status===$('status').value)&&($('portal').value==='all'||j.portal===$('portal').value)&&($('closed').checked||j.is_listed!==false||j.status!=='new')&&($('unverified').checked||j.status!=='new'||j.is_listed===true)&&(!query||[j.company,j.title,j.location,j.notes].join(' ').toLowerCase().includes(query))).sort((a,b)=>$('sort').value==='newest'?(Date.parse(b.posted_at)||0)-(Date.parse(a.posted_at)||0):$('sort').value==='fit'?(b.fit??-1)-(a.fit??-1):b.priority-a.priority)}
function safeLink(url){try{const u=new URL(url);return u.protocol==='https:'?u.href:null}catch{return null}}
function render(){const filtered=selected();$('count').textContent=filtered.length+' matches · '+jobs.filter(j=>j.status==='saved').length+' saved · '+jobs.filter(j=>['applied','interviewing','offer'].includes(j.status)).length+' applied / in progress';$('jobs').replaceChildren();if(!filtered.length)$('jobs').append(el('p','No matches. Try Older / unverified, change filters, or run a discovery scan.','muted'));
for(const j of filtered.slice(0,limit)){const card=el('article',undefined,'card');card.dataset.identity=j.identity;card.append(el('div',j.company,'muted'),el('h2',j.title));const meta=el('div',undefined,'meta');[j.location||'Location not recorded',j.portal,j.posted_at?'Posted '+date(j.posted_at):'Posting date unknown',j.is_listed===true?'Listed · checked '+date(j.checked_at):j.is_listed===false?'Closed':'Not recently verified',j.fit===null?'Jev: Not assessed':'Jev fit: '+Math.round(j.fit*100)+'%'].forEach(t=>meta.append(el('span',t,'badge')));card.append(meta);
const info=el('details');info.append(el('summary','Fit, role details, and prepared answers'));info.append(el('p',j.assessment||'Not assessed. Discovery does not require Jev.','details'));if(j.location_uncertain)info.append(el('p','Verify location eligibility before applying.','error'));if(j.eligibility_reason)info.append(el('p',j.eligibility_reason,'error'));if(j.history_reason)info.append(el('p',j.history_reason,'muted details'));if(j.description)info.append(el('p',j.description,'details'));for(const f of j.fields||[]){const field=el('div',undefined,'field');field.append(el('strong',f.label),el('p',f.answer??f.reason??'No answer','details'));info.append(field)}if(!(j.fields||[]).length)info.append(el('p','No prepared answers. Use the prepare command for this job.','muted'));card.append(info);
const select=el('select');select.setAttribute('aria-label','Tracking status');statuses.forEach(s=>{const o=el('option',label(s));o.value=s;select.append(o)});select.value=j._draftStatus??j.status;select.onchange=()=>j._draftStatus=select.value;const note=el('textarea');note.setAttribute('aria-label','Notes');note.placeholder='Notes, recruiter, interview dates, follow-up…';note.maxLength=10000;note.value=j._draftNotes??j.notes;note.oninput=()=>j._draftNotes=note.value;const actions=el('div',undefined,'actions');const url=safeLink(j.link);if(url){const a=el('a','Open application','primary');a.href=url;a.target='_blank';a.rel='noopener noreferrer';actions.append(a)}actions.append(select);const button=el('button','Save tracking');const feedback=el('span');feedback.setAttribute('role','status');button.onclick=async()=>{button.disabled=true;feedback.textContent='Saving…';try{const r=await fetch('/api/tracking',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({identity:j.identity,status:select.value,notes:note.value})});const body=await r.json();if(!r.ok)throw Error(body.error||'Save failed');Object.assign(j,body);delete j._draftNotes;delete j._draftStatus;feedback.className='saved';feedback.textContent='Saved'+(j.applied_at?' · applied '+date(j.applied_at):'')}catch(e){feedback.className='error';feedback.textContent='Not saved: '+e.message}finally{button.disabled=false}};actions.append(button,feedback);card.append(el('div',undefined,'notes'),note,actions);if(j.applied_at)card.append(el('p','Applied '+date(j.applied_at)+' · user reported','muted'));$('jobs').append(card)}$('more').hidden=filtered.length<=limit}
async function load(){try{const r=await fetch('/api/jobs');if(!r.ok)throw Error('Could not load jobs');const data=await r.json();jobs=data.jobs;$('notice').textContent='70% Jev relevance + 30% recency. '+(data.scan.status?'Scan: '+data.scan.status+'. ':'')+'No automatic applications. Unknown outcomes need verification.';render()}catch(e){$('count').textContent=e.message;$('count').className='error'}}
['search','status','portal','sort','unverified','closed'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',()=>{limit=60;render()}));$('refresh').onclick=load;$('more').onclick=()=>{limit+=60;render()};load();
</script></html>'''
